### ISSUE TITLE
[feat] Implement the functionality to retrieve profile by profileId

### ISSUE THREAD

**Issue by Akashneelesh** [keep-starknet-strange/gitcoin-allo-starknet#15]
Use _profileID as u256 
Down below is the function that is to be implemented in the contract but in cairo :
https://github.com/allo-protocol/allo-v2/blob/4dd0ea34a504a16ac90e80f49a5570b8be9b30e9/contracts/core/Registry.sol#L94

Resources :
https://book.cairo-lang.org/title-page.html
https://book.cairo-lang.org/ch08-01-generic-data-types.html?highlight=struct#structs

If you have any doubts over on how to implement something similar to this you can try discovering few cairo code bases such as :

Unruggable memecoin : https://github.com/keep-starknet-strange/unruggable.meme/tree/main/packages/contracts/src
Blobstream : https://github.com/keep-starknet-strange/blobstream-starknet/tree/main/src

Exclusively for Starknet India team - To onboard new devs from India
Estimated Time taken to complete - 2-3 days (Max)

**Comment by johnwicked7** [comment]
I would like to take this up.

**Comment by kyzan** [comment]
I would like to take this up!

**Comment by Akashneelesh** [comment]
Done @johnwicked7 , you have been assigned to the issue.

Sorry @kyzan , feel free to check other issues as well since its based on fcfs I had to assign to @johnwicked7.

**Comment by Manush-2005** [comment]
Hey I would like to take up this issue
