### ISSUE TITLE
[feat] Implement the functionality of _checkOnlyProfileOwner

### ISSUE THREAD

**Issue by Akashneelesh** [keep-starknet-strange/gitcoin-allo-starknet#17]
Down below is the function that is to be implemented in the contract but in cairo.
https://github.com/allo-protocol/allo-v2/blob/4dd0ea34a504a16ac90e80f49a5570b8be9b30e9/contracts/core/Registry.sol#L331

Resources :
https://book.cairo-lang.org/title-page.html
https://book.cairo-lang.org/ch16-02-00-composability-and-components.html?highlight=assert#example-an-ownable-component

If you have any doubts over on how to implement something similar to this you can try discovering few cairo code bases such as :

Unruggable memecoin : https://github.com/keep-starknet-strange/unruggable.meme/tree/main/packages/contracts/src
Blobstream : https://github.com/keep-starknet-strange/blobstream-starknet/tree/main/src

Exclusively for Starknet India team - To onboard new devs from India
Estimated Time taken to complete - 2-3 days (Max)

**Comment by AkankshaAttavar** [comment]
I would like to take this issue.

**Comment by Akashneelesh** [comment]
Awesome , you've been assigned less go !!

**Comment by Akashneelesh** [comment]
Sorry @AkankshaAttavar , this issue is no longer needed or valid.
