### ISSUE TITLE
[feat] Implement the functionality of _generateAnchor

### ISSUE THREAD

**Issue by Akashneelesh** [keep-starknet-strange/gitcoin-allo-starknet#18]
Internal function to create a _generateAnchor
https://github.com/allo-protocol/allo-v2/blob/4dd0ea34a504a16ac90e80f49a5570b8be9b30e9/contracts/core/Registry.sol#L340

Resources :
https://book.cairo-lang.org/title-page.html
https://book.cairo-lang.org/ch14-01-contract-storage.html?highlight=lega#storage-mappings
- Reference on how to implement keccak256(abi.encodePacked) 
Solidity - https://github.com/celestiaorg/blobstream-contracts/blob/0b4bcf69d1ce96df000da7f95fba8c03aa15a45e/src/lib/tree/namespace/TreeHasher.sol#L33
Cairo - https://github.com/keep-starknet-strange/blobstream-starknet/blob/b74777e5fb479e5b4aa5a1419135e0826343fc37/src/tree/namespace/hasher.cairo#L10
More about it - https://github.com/keep-starknet-strange/alexandria/tree/main/src/encoding

If you have any doubts over on how to implement something similar to this you can try discovering few cairo code bases such as :

Blobstream Solidity : https://github.com/celestiaorg/blobstream-contracts/tree/master/src/lib/tree
Blobstream Cairo: https://github.com/keep-starknet-strange/blobstream-starknet/tree/main/src

Exclusively for Starknet India team - To onboard new devs from India
Estimated Time taken to complete - 2-3 days (Max)

**Comment by RajeshRk18** [comment]
I will take up this one!

**Comment by Akashneelesh** [comment]
Done assigned, less go !!

**Comment by BenFaruna** [comment]
Hello @RajeshRk18 are you still working on this?
I would like to take this up if you're not done or wouldn't be proceeding with it anymore

**Comment by Manush-2005** [comment]
Hi @Akashneelesh, I would like to take this issue

**Comment by byteZorvin** [comment]
I would like to work on this, if its yet to be taken up.

**Comment by Akashneelesh** [comment]
A heads up - This is something thats already worked
