### ISSUE TITLE
[feat] Implement the functionality of _generateProfileId

### ISSUE THREAD

**Issue by Akashneelesh** [keep-starknet-strange/gitcoin-allo-starknet#4]
Issue no. # Implement the functionality of _generateProfileId
Down below is the function that is to be implemented in the contract but in cairo.
https://github.com/allo-protocol/allo-v2/blob/4dd0ea34a504a16ac90e80f49a5570b8be9b30e9/contracts/core/Registry.sol#L375C14-L375C31

Resources :
https://book.cairo-lang.org/title-page.html
https://book.cairo-lang.org/ch14-01-contract-storage.html?highlight=lega#storage-mappings

If you have any doubts over on how to implement something similar to this you can try discovering few cairo code bases such as :

Unruggable memecoin : https://github.com/keep-starknet-strange/unruggable.meme/tree/main/packages/contracts/src
Blobstream : https://github.com/keep-starknet-strange/blobstream-starknet/tree/main/src

Exclusively for Starknet India team - To onboard new devs from India
Estimated Time taken to complete - 2-3 days (Max)

**Comment by jutivia** [comment]
Can I take this issue?

**Comment by Akashneelesh** [comment]
Awesome, you've been assigned less go !!

**Comment by Akashneelesh** [comment]
Hello @jutivia , I believe there has been a duplicate of the same issue. And someone has already taken about that issue before this issue was taken, so I would have to sadly close this up. We will be having more good first issues coming up.
