### ISSUE TITLE
[feat] Implement the functionality of UpdateProfilePendingOwner

### ISSUE THREAD

**Issue by Akashneelesh** [keep-starknet-strange/gitcoin-allo-starknet#9]
Down below is the function that is to be implemented in the contract but in cairo.
https://github.com/allo-protocol/allo-v2/blob/4dd0ea34a504a16ac90e80f49a5570b8be9b30e9/contracts/core/Registry.sol#L253

Resources :
https://book.cairo-lang.org/
https://book.cairo-lang.org/ch14-03-contract-events.html?highlight=event#contract-events

If you have any doubts over on how to implement something similar to this you can try discovering few cairo code bases such as :

Unruggable memecoin : https://github.com/keep-starknet-strange/unruggable.meme/tree/main/packages/contracts/src
Blobstream : https://github.com/keep-starknet-strange/blobstream-starknet/tree/main/src

**Comment by VictoriaAde** [comment]
I would like to work on this.

**Comment by stevencartavia** [comment]
Hi, can I take this? 
I estimate that the time to complete the issue is 2-3 days.

**Comment by Sh0g0-1758** [comment]
I can take this up

**Comment by No-bodyq** [comment]
Hey @Akashneelesh can I work on this

**Comment by Josh-121** [comment]
pls assign. should take few hrs at most

**Comment by Akashneelesh** [comment]
This issue has been assigned to @VictoriaAde . Please feel free to check out for other issues and we will be having more issues coming up.

**Comment by VictoriaAde** [comment]
> This issue has been assigned to @VictoriaAde . Please feel free to check out for other issues and we will be having more issues coming up.

@Akashneelesh I am done with the task, please take a look.
